application: rpidirectory
version: 7
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

inbound_services:
- mail
- xmpp_message

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /css
  static_dir: css

- url: /js
  static_dir: js
  
- url: /images
  static_dir: images

- url: /crawl/.*
  script: cron.driver.app

- url: /debugcrawl.*
  script: cron.crawler.app

- url: /api.*
  script: api.api.app

- url: /stats_api.*
  script: api.stats_api.app
  
- url: /_ah/xmpp/message/chat/
  script: api.chatbot.app
  
- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin

- url: /admin_page.*
  script: admin_page.app
  login: admin

- url: /upload_picture.*
  script: picture.app
  
- url: /picture.*
  script: picture.app
  
- url: /dashboard.*
  script: dashboard.app
  
- url: /detail.*
  script: detail.app
  
- url: /insights.*
  script: insights.app

- url: /ahoy
  script: cron.stats.app
  login: admin

- url: /mapreduce/.*
  script: mapreduce.main.APP
  login: admin

- url: /.*
  script: main.app


libraries:
- name: jinja2
  version: latest