application: rpidirectory
version: 5
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

inbound_services:
- mail
- xmpp_message

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /css
  static_dir: css

- url: /js
  static_dir: js
  
- url: /images
  static_dir: images

- url: /crawl/.*
  script: cron.driver.app

- url: /debugcrawl.*
  script: cron.crawler.app

- url: /api.*
  script: api.api.app
  
- url: /_ah/xmpp/message/chat/
  script: api.chatbot.app
  
- url: /admin_page.*
  script: admin_page.app
  login: admin

- url: /.*
  script: main.app
