application: rpidirectory
version: 1
runtime: python
api_version: 1

inbound_services:
- mail
- xmpp_message

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /crawl/.*
  script: Crawler/Crawler.py

- url: /.*
  script: main.py
