application: rpidirectory
version: 1
runtime: python
api_version: 1

inbound_services:
- mail
- xmpp_message

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /crawl/.*
  script: cron/driver.py

- url: /api.*
  script: api/api.py
  
- url: /admin_page.*
  script: admin_page.py

- url: /.*
  script: main.py
