application: rpidirectory
version: 2
runtime: python
api_version: 1

builtins:
- remote_api: on

inbound_services:
- mail
- xmpp_message

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /crawl/.*
  script: cron/driver.py

- url: /debugcrawl.*
  script: cron/crawler.py

- url: /api.*
  script: api/api.py
  
- url: /_ah/xmpp/message/chat/
  script: api/chatbot.py
  
- url: /admin_page.*
  script: admin_page.py
  login: admin

- url: /.*
  script: main.py
